# https://testdriven.io/blog/dockerizing-django-with-postgres-gunicorn-and-nginx/
version: '3.8'

services:
  web:
    container_name: "Facets-WEB"
    build: ./facets
    #command: python manage.py runserver 0.0.0.0:8000
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./facets/:/usr/src/facets/
    links:
      - elasticsearch:es 
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - elasticsearch
  elasticsearch:
    container_name: "Facets-ES"
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    volumes:
      - ./data/elastic:/var/lib/elasticsearch/data
    environment:
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
