version: "3"

services:
  web:
    container_name: "FACETS-WEB"
    image: python:3.10
    volumes:
      - ./facets:/facets
    links:
      - elasticsearch:es 
    command: bash -c "cd /facets && cp local_settings-docker.py facets/local_settings.py && pip install -r requirements-versions.txt && python manage.py migrate && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - elasticsearch

  elasticsearch:
    container_name: "FACETS-ES"
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    volumes:
      - ./data/elastic:/var/lib/elasticsearch/data
    environment:
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200

  #kibana:
    #image: docker.elastic.co/kibana/kibana:7.16.2
    #container_name: "FACETS-KI"
    #environment:
      #- "ELASTICSEARCH_HOSTS=http://es01-test:9200"
    #ports:
      #- "5601:5601"
