# Generated by Django 4.0.2 on 2022-02-16 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicdoc',
            name='doc_type',
        ),
        migrations.CreateModel(
            name='Descriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(max_length=30)),
                ('voice', models.CharField(max_length=30)),
                ('descr_type', models.CharField(max_length=30)),
                ('value', models.TextField()),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.musicdoc')),
            ],
        ),
    ]
