# Generated by Django 4.0.2 on 2022-04-20 12:32

from django.db import migrations, models
import rest.models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_remove_musicdoc_doc_type_descriptor'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicdoc',
            name='doc',
            field=models.FileField(null=True, upload_to=rest.models.MusicDoc.upload_path),
        ),
        migrations.AddField(
            model_name='musicdoc',
            name='doc_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
