# Generated by Django 4.0.2 on 2022-04-20 12:36

from django.db import migrations, models
import rest.models
import rest.utils


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_musicdoc_doc_musicdoc_doc_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicdoc',
            name='doc',
            field=models.FileField(null=True, storage=rest.utils.OverwriteStorage(), upload_to=rest.models.MusicDoc.upload_path),
        ),
    ]
