# Generated by Django 4.0.2 on 2022-04-27 14:07

from django.db import migrations, models
import rest.models
import rest.utils


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0005_rename_doc_musicdoc_musicfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicdoc',
            name='m21score',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='musicdoc',
            name='musicfile',
            field=models.FileField(blank=True, null=True, storage=rest.utils.OverwriteStorage(), upload_to=rest.models.MusicDoc.upload_path),
        ),
    ]
