# Generated by Django 4.0.2 on 2022-04-28 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0007_remove_musicdoc_musicfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='index',
            old_name='index_name',
            new_name='name',
        ),
    ]
