# Generated by Django 4.0.2 on 2022-04-28 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0009_musicdoc_musicfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='musicdoc',
            name='m21score',
            field=models.TextField(blank=True, null=True),
        ),
    ]
