# Generated by Django 4.0.2 on 2022-05-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0011_remove_musicdoc_musicfile_musicdoc_abcfile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicdoc',
            name='composer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='musicdoc',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
