# Generated by Django 4.0.2 on 2023-01-20 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0012_musicdoc_composer_musicdoc_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metainfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_key', models.CharField(max_length=255)),
                ('meta_value', models.TextField()),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.musicdoc')),
            ],
        ),
    ]
