# Generated by Django 4.0.2 on 2023-02-14 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0013_metainfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('year_birth', models.IntegerField(blank=True, null=True)),
                ('year_death', models.IntegerField(blank=True, null=True)),
                ('dbpedia_uri', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'Person',
            },
        ),
        migrations.AlterField(
            model_name='musicdoc',
            name='composer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest.person'),
        ),
    ]
