# Generated by Django 4.0.2 on 2023-02-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0014_person_alter_musicdoc_composer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
