# Generated by Django 4.0.2 on 2023-02-17 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0015_alter_person_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='dbpedia_uri',
            new_name='dbpedia_url',
        ),
    ]
