# Generated by Django 4.0.2 on 2023-02-24 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0016_rename_dbpedia_uri_person_dbpedia_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='dbpedia_url',
            new_name='wikidata_url',
        ),
    ]
