# Generated by Django 4.0.2 on 2023-06-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0018_person_centuries'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='period',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
