# Generated by Django 4.0.2 on 2023-06-01 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0019_person_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='centuries',
        ),
    ]
