# Generated by Django 4.0.2 on 2022-06-09 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DummyPattern',
        ),
    ]
