# Generated by Django 4.0.2 on 2022-04-29 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicdoc',
            name='index',
        ),
        migrations.DeleteModel(
            name='Index',
        ),
        migrations.DeleteModel(
            name='MusicDoc',
        ),
    ]
