"""
Django settings for facets project.

Generated by 'django-admin startproject' using Django 4.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# From Neuma:
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# MEDIA_ROOT = os.path.join(os.path.dirname(BASE_DIR), 'media')
MEDIA_ROOT = BASE_DIR.as_posix()+ "/media"


MEDIA_URL = '/media/'

NEUMA_ID_SEPARATOR = ":"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-twuznz#^r#ruluxbh)l9=zp%5(h%ndzuqxbju82f0w589cv-pl'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
APPEND_SLASH = True
ALLOWED_HOSTS = ['0.0.0.0', '127.0.0.1', 'localhost', 'neuma-dev.huma-num.fr', ]

# SECURITY SETTING: disable scorelib index to avoid deletion from users
DISABLE_SCORELIB = False

# Application definition

INSTALLED_APPS = [
    'rest.apps.RestConfig',
    'home.apps.HomeConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'drf_yasg',
    'search',
    'loaddata',
    # 'debug_toolbar',
    # 'django_elasticsearch_dsl',
    # 'django_elasticsearch_dsl_drf',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'debug_toolbar.middleware.DebugToolbarMiddleware'
]

ROOT_URLCONF = 'facets.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [(os.path.join(BASE_DIR, 'templates')), ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'home.context_processors.mycontext',
                'django.template.context_processors.debug',
                'django.template.context_processors.media',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'facets.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR.as_posix() + 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

# STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_ROOT = BASE_DIR.as_posix()+ "/static"
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'bootstrap')]

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

NGRAM_SIZE = 3
ALL_PARTS = "all_parts"

# Descriptor types
CHROMATIC_DESCR = "chromatic"
DIATONIC_DESCR = "diatonic"
RHYTHM_DESCR = "rhythmic"
NOTES_DESCR = "notes"
LYRICS_DESCR = "lyrics"

# Search types
CHROMATIC_SEARCH = "chromatic"
DIATONIC_SEARCH = "diatonic"
RHYTHMIC_SEARCH = "rhythmic"
EXACT_SEARCH = "exact"
LYRICS_SEARCH = "lyrics"

ES_QUERY_DIR = os.path.join(BASE_DIR, "static/queries")

ELASTIC_SEARCH = {
    "hosts": [{'host': "localhost", 'port': 9200}]
}

ITEMS_PER_PAGE = 20
SCORES_PER_PAGE = 5

MAX_ITEMS_IN_RESULT = 1000

INTERNAL_IPS = ['127.0.0.1', 'localhost', ]

# Maximum 500MB data for a single bulk loading request
DATA_UPLOAD_MAX_MEMORY_SIZE = 524288000

try:
    from facets.local_settings import *
    print("local settings .... ok")
except ImportError as error:
    print(error)

